const WALL = 1;
const FLOOR = 0;

const MAZE = [
    [WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL],
    [WALL, FLOOR, FLOOR, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, WALL,FLOOR, FLOOR, FLOOR, FLOOR, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL],
    [WALL, FLOOR, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, WALL, FLOOR, WALL, FLOOR, FLOOR, FLOOR, WALL, FLOOR, FLOOR, FLOOR, FLOOR, WALL, FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, WALL, FLOOR, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL],
    [WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL],
    [WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL],
    [WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, FLOOR,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL, WALL,WALL, WALL],
    [WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL],
    [WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL],
    [WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, FLOOR, WALL, FLOOR,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL, WALL, WALL, WALL,WALL, FLOOR, WALL, WALL,WALL, WALL, WALL, FLOOR,WALL],
    [WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR, FLOOR,WALL, FLOOR, FLOOR, FLOOR,WALL],
    [WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL, WALL,WALL]
];
(function () {
    let divMaze = document.getElementById("maze");
    for (let line of MAZE) {
        let divLine =  document.createElement("div");

        for (let cell of line) {
            let divCell =  document.createElement("div");
            if(cell === FLOOR){
                divCell.classList.add("floor");
            }
             else if (cell === WALL){
                divCell.classList.add("wall");
            }
            divLine.appendChild(divCell);
        }
        divMaze.appendChild(divLine);
    }
})();